### ISSUE TITLE
TypeError: _Guidance.__call__() got an unexpected keyword argument 'silent'

### ISSUE THREAD

**Issue by rodrigocostacamargos** [interpretml/TalkToEBM#4]
I encountered an issue when trying to run the following code in the TalkToEBM package:

llm_descripe_dict = {k: kwargs[k] for k in dict(kwargs) if k in llm_descripe_kwargs}
prompt = prompts.describe_graph_cot(
    graph, num_sentences=num_sentences, **llm_descripe_dict
)

return guidance(prompt, llm, silent=True)()["cot_graph_description"]

Error Message:
TypeError: _Guidance.__call__() got an unexpected keyword argument 'silent'

Steps to Reproduce:
Install the TalkToEBM package from GitHub.

Run the code snippet:
graph_description = t2ebm.llm_describe_ebm_graph(llm, ebm, 0) # feature 0, 'HomePlanet'
print(textwrap.fill(graph_description, 80))

Expected Behavior:
The code should execute without errors and return the description of the graph.

Actual Behavior:
The code raises a TypeError indicating that the silent keyword argument is unexpected in the _Guidance.__call__() method.

Environment:
TalkToEBM version: latest from GitHub
Operating System: Windows 10

Please let me know if there is a workaround for this issue or if I need to update any dependencies. 
Thank you!

**Comment by rodrigocostacamargos** [comment]
Hi @sbordt,
I have successfully updated to version 0.1.0 of the t2ebm package, and everything is working perfectly now. Thank you for fixing the bug and ensuring compatibility with the latest versions of the dependent packages. I will let you know if I encounter any further issues.

**Comment by sbordt** [comment]
Great to hear that it works for you now. I close this issue, but let us know if you encounter any further issues.
