### ISSUE TITLE
Potential Typos and Incorrect Variable Use in Prompts

### ISSUE THREAD

**Issue by IkokObi** [interpretml/TalkToEBM#5]
Thank you for your great research. I appreciate that you are sharing your research code as open source, which has allowed me to run the code myself and deepen my understanding. I noticed a few things in the `t2ebm/prompts.py` while running the code.

## 1. Typos in Prompt

- There is a typo in the `summarize_ebm` prompt where "importaces" should be corrected to "importances".
- There is a typo in the `describe_graph_cot` prompt where "suprising" should be corrected to "surprising".

## 2. Logic Error

https://github.com/interpretml/TalkToEBM/blob/34ed6528a4e37d2b95664a7452f341fe83deb7af/t2ebm/prompts.py#L92-L93
In the if statement of `summarize_ebm` that checks for a non-empty dataset_description, the code appears to be using graph_descriptions instead of dataset_description when adding the dataset information to the message. This could lead to incorrect information being passed to the LLM.

Thank you for your time and consideration!

**Comment by sbordt** [comment]
Hi @IkokObi . Thanks for reporting these bugs! I updated the package to version 0.1.1, which should fix the reported bugs. Let me know if you encounter any other problems with the package.

**Comment by sbordt** [comment]
I will close this issue for now, but feel free to open a new issue should you find any more bugs in the code :)
