### ISSUE TITLE
Error in importing t2ebm

### ISSUE THREAD

**Issue by DanialNejad** [interpretml/TalkToEBM#6]
Hi,
I faced the following error importing t2ebm despite my API key being valid.

OpenAIError                               Traceback (most recent call last)
[<ipython-input-16-5369a6029be3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import t2ebm
      2 
      3 t2ebm.set_api_key("my API key")

4 frames
[/usr/local/lib/python3.10/dist-packages/openai/_client.py](https://localhost:8080/#) in __init__(self, api_key, organization, project, base_url, timeout, max_retries, default_headers, default_query, http_client, _strict_response_validation)
    103             api_key = os.environ.get("OPENAI_API_KEY")
    104         if api_key is None:
--> 105             raise OpenAIError(
    106                 "The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable"
    107             )

OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by sbordt** [comment]
Hi @DanialNejad . I suggest you set the OPENAI_API_KEY environment variable. t2ebm does not have a function set_api_key. Let me know if this works for you.

**Comment by DanialNejad** [comment]
@sbordt, I appreciate your guidance. It is effective for me.
